package(
    default_visibility = ["//visibility:public"],
    default_applicable_licenses = ["//:license"],
)

# Cortex-M23, Cortex-M33, Cortex-M35P
constraint_value(
    name = "armv8-m",
    constraint_setting = "//cpu",
)
